### PR TITLE
Update PDF.js library to v2.10.377

### LINKED ISSUE #3: Upgrade PDF.js library
PR here: https://github.com/backdrop-contrib/pdfjs/pull/2

### PR DESCRIPTION
**Pull request by laryn**
Fixes #3

### CODE REVIEW

**Comment by laryn** [comment]
@opi I've done some basic testing and this seems to work as a drop-in replacement for the current version.

**Comment by opi** [comment]
@laryn it seems that I don't have write access anymore, and can't perform the merge...

**Comment by laryn** [comment]
@klonos  can you help with these permissions?

**Comment by klonos** [comment]
Done:
image

@opi can you please try again now?

**Comment by opi** [comment]
yeah, I can haz merge

**Comment by opi** [comment]
@laryn do you want to take the ownership for this module ? I do not have any free time to work on backdrop anymore

**Pull request merged**
